spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/openbloglite
    username: openbloglite
    password: 8E(q88f{Cs;R
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
